### PR TITLE
Change to TZIP-024

### PR DESCRIPTION
**Pull request by sbihel**
- [ ] The current implementation assumes TZIP-024 means `tzprofile`. Depending on the result of the conversation in #58 it will need to be tweaked.
- [x] Publish the new version of the SDK

### CODE REVIEW

**Comment by wyc** [comment]
Let’s see if we can hold off on this...there have been some deployments with tzip-23

**Comment by sbihel** [comment]
The metadata URL stays the same so old contracts will continue working

**Comment by krhoda** [comment]
I'm running into several issues testing this, one is that the created credentials get downloaded as `undefined` rather than the JSON file. Secondly, don't see existing profiles.

I'm going to do some more testing to figure out what the exact parameters of the problem are.

**Review by krhoda — APPROVED** [review]
Very simple changes, was working locally, will retest the CF build. Assuming it's the same this is good to merge.

Edit: CF build works fine. I'm ready to merge this.

**Pull request merged**
